
services:
  php:
    build:
      context: ./docker/php
    container_name: weather_app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - .:/var/www/weather
    networks:
      - weather

  nginx:
    container_name: weather_nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/weather
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - weather

networks:
  weather:
    driver: bridge


