
services:
  app:
    build:
      context: ./docker/php
    container_name: weather_app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - .:/var/www
    networks:
      - weather
networks:
  weather:
    driver: bridge


